### ISSUE TITLE
-- renders as a long -, can we stop that ?

### ISSUE THREAD

**Issue by aneojgurhem** [Barbapapazes/slidev-theme-aneo#101]

**Comment by Barbapapazes** [comment]
Maybe that's Poppin, will investigate to use another font to display `pre`

**Comment by Barbapapazes** [comment]
Can't reproduce, can you provide a production of this issue?

**Comment by Barbapapazes** [comment]
You're in a list, not in code. So, you need to use backticks.

```md
- `--rm` option to remove the container after execution
```

**Comment by Barbapapazes** [comment]
Will add it to docs.

**Comment by aneojgurhem** [comment]
That's annoying as I have a lot of them. I'll change it anyway...

**Comment by aneojgurhem** [comment]
![image.png](https://volta.s3.fr-par.scw.cloud/image_51d00c143e.png)
The backticks are rendered. Can we remove them ?

**Comment by Barbapapazes** [comment]
The issue is not slidev but Poppin, font used by aneo.

And will investigate how code blocks are rendered.

**Comment by Barbapapazes** [comment]
> That's annoying as I have a lot of them. I'll change it anyway...

D'un point de vue sémantique, englober `--rm`dans un block de code, ça fait sens.

Jr peux ajouter une section dans la documentation sur les bonne pratique.

**Comment by aneojgurhem** [comment]
Je suis d'accord et c'est pour ça que je l'ai fait. Mais j'en avais plein... Du coup j'étais deg. Je ne sais pas si cette section est nécessaire surtout pour adresser le fait qu'il est mieux de mettre du code dans un block de code.
