### ISSUE TITLE
minDepth and maxDepth does not seem to be taken into account

### ISSUE THREAD

**Issue by aneojgurhem** [Barbapapazes/slidev-theme-aneo#86]

**Comment by Barbapapazes** [comment]
Can you provide a reproduction and a more detail exemple of your use case?

**Comment by aneojgurhem** [comment]
I cannot launch the example.md from this repo. I have an issue with `npm ci`. I'll create an issue about that.

**Comment by Barbapapazes** [comment]
Yep, I need to rewrite the contributing section

**Comment by aneojgurhem** [comment]
I did not understand that toc options should be put in the Toc html tags. I was putting them in the layout !
