### ISSUE TITLE
rework h2

### ISSUE THREAD

**Issue by aneojgurhem** [Barbapapazes/slidev-theme-aneo#87]
If we use h1 for slide sections, we cannot use it as per slide title. h2 is a good choice for replacement. Therefore, we need to render h2 almost like h1 (especially for the subtitle which is a great feature).

**Comment by Barbapapazes** [comment]
Is this issue style relevant since #85 is cloded ?

**Comment by aneojgurhem** [comment]
Yes, I'm mainly interested in the subtitle feature that was coming with h1. It does not work with h2 since I use h1 in section slides and h2 in default slides

**Comment by Barbapapazes** [comment]
Ok, can you provide a exemple summary (what your perfect summary looks like?)?

**Comment by aneojgurhem** [comment]
The one there was with h1 was great

**Comment by aneojgurhem** [comment]
I do not have a better idea

**Comment by aneojgurhem** [comment]
As you can see in #137, the subtitle in defaut slides with h2 is not rendered compared to the ones in default slides with h1.
